# Streamlit Cloud Secrets Configuration
# Copy this file and add your actual API credentials

[api]
# Get your API key from https://console.mistral.ai/
MISTRAL_API_KEY = "your-actual-mistral-api-key-here"

# Instructions:
# 1. Replace the placeholder values above with your actual Mistral API credentials
# 2. Upload this file to your Streamlit Cloud app's secrets
# 3. The app will automatically use these credentials for AI-powered features
# 4. Without these secrets, the app will fallback to rule-based extraction
